#!/bin/python3
import json,os,urllib.request
os.makedirs('/mnt/shared/animethemes-db-dumps',exist_ok=1)
os.chdir('/mnt/shared/animethemes-db-dumps')
urlopen=lambda u:urllib.request.urlopen(urllib.request.Request(u,headers={'User-Agent':'curl'}))
with urlopen('https://api.animethemes.moe/dump')as r:dump=json.load(r)['dumps'][-1]
with urlopen(dump['link'])as r:moe=r.read()
with open(dump['path'],'bw')as f:f.write(moe)
os.system('rm `ls -t|tail +3`')
